### ISSUE TITLE
Providing bootstrapped release sources

### ISSUE THREAD

**Issue by seki98** [rrthomas/recode#10]
I wonder if it would be possible, to provide also bootstrapped sources.

After the local directory is `bootstrap`ped , `make dist` can be executed, which will produce a tarball containing everything needed for `configure` and `make` scripts.

The generated tarball does not need additional sources to be download, after the release sources have been downloaded and extracted.

Steps:
```
$ git clone https://github.com/rrthomas/recode.git && cd recode
$ ./bootstrap
$ ./configure
$ make
$ make dist
$ ls
... recode-3.7.tar.gz ...
```

Please let me know your ideas, having the sources at least alongside the existing ones(which don't include gnulib sources) might be useful for linux distributions.

**Comment by rrthomas** [comment]
The release tarballs are built from `make dist`.
