### ISSUE TITLE
FSF address in copyright notice

### ISSUE THREAD

**Issue by rffontenelle** [rrthomas/recode#17]
I noticed that [src/main.c](https://github.com/rrthomas/recode/blob/master/src/main.c#L166) prints the copyright notice including FSF's address for GNU GPLv3.

Just a minor thing: GNU GPLv3 doesn't include FSF's address in the copyright notice, it was replaced with link to the license in GNU website. Maybe you want to do the same?

So, instead of:

```
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foundation,
Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
```

there is now:

```
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
``` 

See: https://www.gnu.org/licenses/gpl-3.0.html#howto

**Comment by rrthomas** [comment]
Fixed!
