### ISSUE TITLE
Old COPYING-LIB

### ISSUE THREAD

**Issue by ppisar** [rrthomas/recode#21]
I have two issues with COPYING-LIB:

The license text quotes Free Software Foundation postal address that is not valid anymore. Current one can be found at <https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt>. Please update the license wording to deliver an up-to-date address to your users.

The license file carry an LGPLv2 text, but there is actually no source file with that license declaration. E.g. src/ucs.c and src/recode.h are LGPLv3+. I recommend replacing the COPYING-LIB file with LGPLv3 license text <https://www.gnu.org/licenses/lgpl-3.0.txt>. That will be more accurate and less confusing.

**Comment by rrthomas** [comment]
Thanks for letting me know. I have updated `COPYING-LIB` to LGPLv3.

**Comment by ppisar** [comment]
Thank you for the prompt answer.

Now I noticed that two header files src/recode.h and src/recodext.h also have the old address.

**Comment by rrthomas** [comment]
I've fixed the source headers too, thanks.
