### ISSUE TITLE
Set soname from version

### ISSUE THREAD

**Issue by ppisar** [rrthomas/recode#22]
I'm upgrading recode in Fedora from 3.6 to 3.7.1 and I noticed the librecode library removed module_libiconv() function as well as a public recode_outer structure removed some members. These changes break ABI of the library and hence the library should change soname. However, that did not happen and it is still "librecode.so.0".

Was the ABI change intentional? Would you mind changing the soname (-version-info argument in src/Makefile.am)? Or do you think that 3.7 exists so long that changing the soname now would be counterproductive?

**Comment by rrthomas** [comment]
As far as I can tell, the soname has always been hardwired. You're quite correct, the soname should change.

**Comment by rrthomas** [comment]
I don't think it's too late to change the soname, as recode 3.7 is not (yet) widely distributed.
