### ISSUE TITLE
version badge on README.md

### ISSUE THREAD

**Issue by okias** [rrthomas/recode#26]
Hey,

you may consider putting https://repology.org/project/recode/badges on your README.md, it's nice to directly see if your distro use up-to-date version.

**Comment by rrthomas** [comment]
Thanks for the suggestion! I would be happy to use the "Tiny badge with latest packaged version(s)". Could you provide a patch for that, please?

Also, could you explain one thing that I can't find explained on the page: why is "3.6" green, and "3.7.6" is green, but "3.7.1" is red? 3.6 is very old, and needs updating! It gives a misleading impression.

**Comment by okias** [comment]
Probably when minor version is at some level it won't highlight it. Maybe they care only about patch-level?

**Comment by rrthomas** [comment]
Ping? Still happy to have this patch if you'd like; otherwise, please close the issue.

**Comment by okias** [comment]
Sorry, I tried put madge into README.md and it didn't worked correctly back then, for now I'm closing.

**Comment by rrthomas** [comment]
Thanks for responding!
