### ISSUE TITLE
Android Platform

### ISSUE THREAD

**Issue by tathastu871** [rrthomas/recode#36]
SignFORTIFY: %n not allowed on Android

See
https://github.com/termux/termux-packages/issues/4381

**Comment by rrthomas** [comment]
Thanks for this, @tathastu871. Git master should now be fixed; I've updated gnulib to get a version that has specific Android support in its `vasnprintf` implementation.

**Comment by tathastu871** [comment]
Works

**Comment by rrthomas** [comment]
Thanks! If you need to file another issue, please do so.
