### ISSUE TITLE
“Too many open files” when low open file ulimit

### ISSUE THREAD

**Issue by kugland** [rrthomas/recode#40]
Recode fails with `Too many open files` when given more files than the soft limit on open file descriptors. Isn’t it possible to close the descriptors after recoding each file?

```
% ulimit -Sn 100
% seq 1 100 | xargs touch
% recode latin1..utf8 *   
pipe (): Too many open files
zsh: segmentation fault (core dumped)  recode latin1..utf8 *
```

Memory usage increases monotonically when recoding thousands of files because of this.

**Comment by rrthomas** [comment]
Thanks for this report; I'll make a new release shortly.

**Comment by kugland** [comment]
@rrthomas, why did this cause a segmentation fault?

Isn’t the process continuing after the call to `pipe()` fails?

https://github.com/rrthomas/recode/blob/de974299ccc9f69a829e22fb53c37403a7bb942d/src/task.c#L301

**Comment by rrthomas** [comment]
This is a good question, I was wondering myself. In fact, `recode` crashes while trying to output an error message; I'll look into it!

**Comment by rrthomas** [comment]
I have fixed this bug; thanks!
