### ISSUE TITLE
invalid UTF8 BOM is not removed 

### ISSUE THREAD

**Issue by PSLLSP** [rrthomas/recode#55]
I have several UTF-8 files those start with UTF-8 BOM, `<feff>` [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark)

I joined several such files to just one file with `cat file*.csv > test.csv`. The problem of the result is that it contains several BOMs and utility that I use to process `test.csv` reports that input data is invalid.

I tried to remove BOM from the file with `recode u8..u8 < test.csv > test1.csv` but BOM were not removed.

Example

Create test files:
```
for I in 1 2 3; do echo -e "\xef\xbb\xbfTEST ${I}" > "test-${I}.txt"; done
cat test-[123].txt > test-bom.txt
recode u8..u8 < test-bom.txt > test-bom1.txt
```
Test the result:

```
$ file test-1.txt 
test-1.txt: UTF-8 Unicode (with BOM) text

$ ls -l test*.txt
-rw-rw-r-- 1 user user 10 Mar 29 17:25 test-1.txt
-rw-rw-r-- 1 user user 10 Mar 29 17:25 test-2.txt
-rw-rw-r-- 1 user user 10 Mar 29 17:25 test-3.txt
-rw-rw-r-- 1 user user 30 Mar 29 17:30 test-bom.txt
-rw-rw-r-- 1 user user 30 Mar 29 17:30 test-bom1.txt
```

Files `test-[123].txt` have length 10 bytes, when I join them length is 30 (no BOM was removed). File that was processed with `recode` utility has length 30 bytes, no BOM was removed :-(

---
Tested with Linux Mint 20.3 and 21.2

```
$ recode --version
Free recode 3.6
Written by Franc,ois Pinard <pinard@iro.umontreal.ca>.

Copyright (C) 1990, 92, 93, 94, 96, 97, 99 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

---

UPDATE

Maybe this is not a bug. BOM in the middle of file is not `BOM` but `ZWNBSP` (written at Wikipedia) and then it is OK that it is not removed by `recode`. The problem is when several UTF-8 files with BOM are joined together, then BOM are written in the middle of file and are source of troubles; there is no easy way to address this. `dos2unix` can remove BOM but it only removes it from the beginning of the file. Other way was to use `sed` with escape sequences (similar escape sequence was used to create test file), not nice. 

`grep` is confused with BOM:

```
$ grep "." test-[12].txt  # just print what is in files
test-1.txt:﻿TEST 1
test-2.txt:﻿TEST 2

$ grep "^TEST" test-[12].txt  # confused, it finds nothing

$ grep "^.TEST" test-[12].txt  # line starts with an invisible character, now it finds TEST
test-1.txt:﻿TEST 1
test-2.txt:﻿TEST 2
``` 

---

I believe this is a bug: `recode` fails with an error when I try to translate from UTF-8 (with BOM) to other encoding, like WINDOWS-1250 (cp1250):

```
$ recode u8..cp1250 < test-1.txt > test-cp1250.txt
recode: Invalid input in step `UTF-8..CP1250'
```

BOM can be removed with utility `dos2unix`. `recode` then can convert file from encoding UTF-8 (u8) to WINDOWS-1250 (cp1250):

```
$ dos2unix < test-1.txt > test-1-u8.txt
$ recode u8..cp1250 < test-1-u8.txt > test-1-cp1250.txt

$ ls -l test-1.txt test-1-u8.txt test-1-cp1250.txt
-rw-rw-r-- 1 user user 10 Mar 29 19:28 test-1.txt
-rw-rw-r-- 1 user user  7 Mar 30 12:48 test-1-u8.txt
-rw-rw-r-- 1 user user  7 Mar 30 12:48 test-1-cp1250.txt
```

I tried the same with `iconv` and it fails in the same way, it cannot convert UTF-8 file starting with BOM to encoding CP1250:

```
$ iconv -f UTF-8 -t CP1250 < test-1.txt > test-1-cp1250-iconv.txt
iconv: illegal input sequence at position 0

$ iconv --version
iconv (Ubuntu GLIBC 2.35-0ubuntu3.6) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Ulrich Drepper.
```

**Comment by rrthomas** [comment]
Thanks for this report. My understanding aligns with yours: BOM at the start of a file is not the same as ZWNBSP elsewhere. So, I think that recode should elide BOMs from files after the first in a sequence. However, the problem in the case you give is that the files were already concatenated: recode has no way to tell that the BOMs in the middle are not intentional ZWNBSPs.

So, I don't think there's anything Recode can do here.
