### ISSUE TITLE
html: Incomplete numeric entities result in invalid NUL char 

### ISSUE THREAD

**Issue by ccbenny** [rrthomas/recode#59]
When an entity like `&#;` or similar, without any digit, is encountered, the `html` decoder returns a NUL char.  The behaviour here is debatable, but since NUL chars are invalid anyway in HTML and XML, it seems better to just declare such entities as invalid and keep the original characters.  That is what Firefox does.  Patch follows.

**Comment by ccbenny** [comment]
[0001-src-html.c-Do-not-decode-invalid-numeric-entities-fi.patch.gz](https://github.com/user-attachments/files/17001962/0001-src-html.c-Do-not-decode-invalid-numeric-entities-fi.patch.gz)

**Comment by rrthomas** [comment]
Patch applied; many thanks! If any future patches could be PRs, that would be appreciated, but not at all required.

**Comment by ccbenny** [comment]
Thanks.
