### ISSUE TITLE
Recode HTML Entity &apos; to UTF-8

### ISSUE THREAD

**Issue by brileyd** [rrthomas/recode#60]
I need to recode some html entities to text.  However, it seems the apostrophe isn't recognized by name.  If I convert the following using "recode h":
```
&nbsp; 	&#160; 	
&lt; 	&#60; 	
&gt; 	&#62; 	
&amp; 	&#38; 	
&quot; 	&#34; 	
&apos; 	&#39; 	
&cent; 	&#162; 	
&pound; 	&#163; 	
&yen; 	&#165; 	
&euro; 	&#8364; 	
&copy; 	&#169; 	
&reg; 	&#174;
```

I get:
```
< 	<
> 	>
& 	&
" 	"
&apos; 	'
¢ 	¢
£ 	£
¥ 	¥
€ 	€
© 	©
® 	®
```

So everything other than `&apos;` seems to work.

**Comment by rrthomas** [comment]
`&apos;` is not a valid HTML entity in any version of HTML that Recode supports. I would be happy to accept a patch to support HTML 5.0, which does include `&apos;`. Recode supports `&apos;` in XML.
